Resolving clippy warning
BurntSushi/aho-corasick pull request #135
Opened 2023-11-14 00:21 UTC by allaboutevemirolive

I've cut the Clippy warnings in half, dropping from 57 to 28. The remaining warnings likely require changes to variable names and the maintainer's perspective.

@BurntSushi

2023-11-14 00:30 UTC, BurntSushi requested changes
I don't really agree with most of these changes. I don't feel terribly strong about most of them, but generally prefer to not accept most of these. This is why I don't have Clippy setup to run. (I realize I could pick and choose which lints I want to enable, but this is a lot of work to do across the number of repos I maintain and just ultimately isn't worth it for me.)

I marked the changes that I agree with.

2023-11-14 00:30 UTC, BurntSushi commented on src/dfa.rs
> +            prefilter: nnfa.prefilter().cloned(),
I agree with this one.

2023-11-14 00:30 UTC, BurntSushi commented on src/packed/api.rs
> +        match self.searcher.find_in(self.haystack, self.span) {
I agree with this one.

2023-11-14 00:30 UTC, BurntSushi commented on src/nfa/contiguous.rs
> +    fn transitions(&self) -> impl Iterator<Item = (u8, StateID)> + '_ {
I agree with this one.

2023-11-14 00:30 UTC, BurntSushi commented on src/packed/pattern.rs
> +            .field("lit", &String::from_utf8_lossy(self.0))
I agree with this one.

2023-11-14 00:30 UTC, BurntSushi commented on src/packed/pattern.rs
> +        self.0
I agree with this one.

2023-11-14 00:30 UTC, BurntSushi commented on src/util/prefilter.rs
> +            .find_in(haystack, span)
I agree with this one.

2023-11-14 00:30 UTC, BurntSushi commented on src/util/prefilter.rs
> +                    bytes[len] = b;
I agree with this one.

2023-11-14 00:30 UTC, BurntSushi commented on src/util/prefilter.rs
> +        let mut rarest = match bytes.first() {
Agree.

2023-11-14 00:30 UTC, BurntSushi commented on src/util/prefilter.rs
> +        if let Some(&byte) = bytes.first() {
Agree.

2023-11-14 21:03 UTC, allaboutevemirolive commented
Is this okay with you? @BurntSushi

2024-03-27 20:37 UTC, BurntSushi approved these changes
Thanks!

2024-03-27 20:37 UTC, merged